name: Run Tenant Security Tests
on: 
      workflow_dispatch:
      push:
permissions:
      id-token: write
      contents: read


jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Run Maester action
      uses: maester365/maester@main
      with:
        client_id: ${{ secrets.CLIENT_ID }}
        tenant_id: ${{ secrets.TENANT_ID }}
    - name: Azure PowerShell Action
      uses: Azure/powershell@v2
      with:
        # Specify the Az PowerShell script here.
        inlineScript: |
          dir .
          dir .\
          dir .\test-results
            